### ISSUE TITLE
The license field in composer.json is wrong

### ISSUE THREAD

**Issue by williamdes** [dompdf/php-font-lib#116]
While working on the Debian packaging I did notice that it's not LGPL-3.0 but LGPL-2.1

https://github.com/dompdf/php-font-lib/blob/1f8f77ee56f275e5369c4ef39b16ade7ea5adf34/composer.json#L6

**Comment by bsweeney** [comment]
Indeed. Originally reported in #86. I'll take a look at fixing while prepping the next release.

**Comment by williamdes** [comment]
Thanks, please also update the composer package name?
