### ISSUE TITLE
New test

### ISSUE THREAD

**Issue by williamdes** [dompdf/php-font-lib#117]
I wrote a new test at Debian, feel free to copy it https://salsa.debian.org/php-team/pear/php-font-lib/-/commit/8eaf263e4e46e058c10092bb2fc8f57d166353d7#c7b64e342fbabe70eb0b971e27dbfec490fccf92_0_54

Or to close this issue :)

Yeah I had to remove the font files because of the missing licences for them in `sample-fonts`

**Comment by bsweeney** [comment]
I'll need to look at the fonts to see if there's an applicable license. Otherwise, I'll look for something that's compatible with the library license.

**Comment by bsweeney** [comment]
The AFM files included with Dompdf are for the PDF core fonts. The license for those is in the mustRead.html.

I will look at what we need to do for the DejaVu fonts. The UFM files were generated by the Dompdf team and not provided by the DejaVu team.

**Comment by williamdes** [comment]
> The AFM files included with Dompdf are for the PDF core fonts. The license for those is in the mustRead.html.

I probably missed them, a license file would be great and more explicit

> I will look at what we need to do for the DejaVu fonts. The UFM files were generated by the Dompdf team and not provided by the DejaVu team.

Can you provide a way to re-build them?
We "can not" accept non human readable built files, we need to re build them from source at Debian

**Comment by bsweeney** [comment]
The UFM files are human readable. They're just a delimited text file with a format similar to the AFM format. The files were built using php-font-lib so re-building them is straightforward:

```
$font = FontLib\Font::load("/path/to/file.ttf");
if ($font instanceof FontLib\TrueType\Collection) {
    $font = $font->getFont(0);
}
$font->parse();
$font->saveAdobeFontMetrics(__DIR__ . '/output/' . basename($test_file) . '.ufm');
```

**Comment by williamdes** [comment]
Thank you, you can close this issue now or when you cherry-picked my test if you want to

**Comment by bsweeney** [comment]
I'll keep this open so I don't forget to review that test.

**Comment by bsweeney** [comment]
Suggestions on how to handle this in php-font-lib?

Intel Clear is licensed under Apache 2.0
https://github.com/intel/clear-sans

Noto fonts are licensed under OFL
https://fonts.google.com/noto/specimen/Noto+Sans+Shavian/about

**Comment by williamdes** [comment]
A folder for fonts in tests with a license file in each subfolder?
And if possible a txt with where each font was downloaded?

**Comment by bsweeney** [comment]
PR #130 adds that new test and modifies the font structure. I also switched from Intel Clear-Light to the W3C font Ahem, which is intended for unit testing so may prove useful in future test development.

Let me know if you have any feedback.
