### ISSUE TITLE
How install via composer?

### ISSUE THREAD

**Issue by marciojalber** [dompdf/php-font-lib#137]
How can I install via composer? Don't works when I tried with composer **require dompdf/php-font-lib**. Thanks

**Comment by danielscsc** [comment]
> How can I install via composer? Don't works when I tried with composer **require dompdf/php-font-lib**. Thanks

This worked for me in the past:
`composer require phenx/php-font-lib`

**Comment by bsweeney** [comment]
Noting that the namespace was updated so dompdf/php-font-lib is now the preferred package name (though the old name still works).
