### ISSUE TITLE
Chrome & Firefox errors when loading generated subset TTF fonts, for all fonts

### ISSUE THREAD

**Issue by oxygen** [dompdf/php-font-lib#41]
I have generated a subset font for each font with only the letters from the font's file name.
I was going to use these subset TTF files for a preview of the font.

Using these fonts: https://github.com/google/fonts
All 1736 fonts fails with one of these errors:

(index):1 OTS parsing error: incorrect entrySelector for table directory
(index):1 OTS parsing error: hhea: misaligned table

This is the code I am using to generate the subset files:

```
$tmp=tempnam(sys_get_temp_dir(), $strFontFamily);
$fontFile=\FontLib\Font::load($arrFont["path"]);
$fontFile->parse();

$fontFile->setSubset($strFontFamily);
$fontFile->reduce();

$fontFile->open($tmp, FontLib\BinaryStream::modeWrite);
$fontFile->encode(array("OS/2"));
$fontFile->close();
```
##

**Comment by oxygens** [comment]
The original fonts work as a preview without any errors in Internet Explorer and Chrome.
Only the subset fonts fail.

**Comment by oxygens** [comment]
May be useful, the error "incorrect entrySelector for table directory" is thrown here:
https://searchcode.com/codesearch/view/26727670/
Line 242

**Comment by jepsonwu** [comment]
Hi.did you have a solution?I have the same problem.

**Comment by jepsonwu** [comment]
Hi sir oxygen.did you have a solution?I have the same problem.

**Comment by jepsonwu** [comment]
Hi sir oxygen.did you have a solution?I have the same problem. @oxygen

**Comment by oxygen** [comment]
No, and I vaguely remember reporting it to Google, but most likely I didn't.

This needs to be reported to Chrome and Firefox and see if its their fault.

I mean I don't know enough about fonts to tell where the fault lies.

**Comment by roberthenniger** [comment]
@oxygen, @jepsonwu have the same issue and was wondering on how you solved your subset problem? We also need font previews and they do not work when created over php-font-lib.

**Comment by wilbur-oo** [comment]
@oxygen @jepsonwu @roberthenniger

**Comment by wilbur-oo** [comment]
@oxygen @jepsonwu @roberthenniger I had the same problem
![image](https://user-images.githubusercontent.com/7148309/79323327-a15bbd80-7f40-11ea-897f-1f282c4a4f32.png)

**Comment by roberthenniger** [comment]
@PhenX is there a solution to this problem? How could we solve this issue since it would be awesome to create subsets without installing a big tech stack as npm-fontkit or something similar.

**Comment by oluwasayo** [comment]
> @PhenX is there a solution to this problem? How could we solve this issue since it would be awesome to create subsets without installing a big tech stack as npm-fontkit or something similar.

FWIW, I arrived at this issue from using fontkit :)

**Comment by bsweeney** [comment]
After looking into this a bit more it appears that generated TrueType font files may not fully conform to the spec. I've tested a number of fonts and identified the spec compliance issues that will prevent a font from loading in the browsers. I'm tracking the full list of non-compliance issues in #123.

The next release will address the bare minimum of issues identified so that web browsers will load a generated font.

**Comment by oxygen** [comment]
Thank you!!!
