### ISSUE TITLE
Undefined offset: 1056 in php-font-lib-master/src/FontLib/Table/Type/post.php

### ISSUE THREAD

**Issue by onassar** [dompdf/php-font-lib#63]
`Undefined offset: 1056 in /php-font-lib-master/src/FontLib/Table/Type/post.php`
This happens when using the following font file:
https://s3-us-west-2.amazonaws.com/app.getstencil.com/upld86d1d1bf

Here's a screenshot of my OSX, showing that the file seems to be a proper font file:
![](https://i.imgur.com/wAyrPsj.png)

**Comment by onassar** [comment]
It's actually all of the font families Google provides in this font:
https://fonts.google.com/specimen/Zilla+Slab?selection.family=Zilla+Slab

**Comment by onassar** [comment]
Bump!

**Comment by usama-gh** [comment]
Still happening for me as well. Were you able to find a solution?
